"""Build offline preview assets inside this skill; optionally publish a site copy."""
import argparse
import json
from pathlib import Path
import shutil


ROOT = Path(__file__).resolve().parent
PREVIEW = ROOT.parent / 'preview'
RUNTIME_FILES = ('expression-preview.html', 'expression-preview.js',
                 'expression-runtime.js', 'expression-schema.js',
                 'expression-demo.js', 'svg-preview.html')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--publish', type=Path, help='Explicit destination for a repository/site preview copy')
    args = parser.parse_args()
    schema = json.loads((ROOT / 'expression.schema.json').read_text(encoding='utf-8'))
    demo = {
        'name': 'contract-fixture.svg',
        'svg': (ROOT / 'examples/contract-fixture.svg').read_text(encoding='utf-8'),
        'rig': json.loads((ROOT / 'examples/controls.example.json').read_text(encoding='utf-8')),
    }
    for name, variable, data in [('expression-schema.js', 'AstraExpressionSchema', schema),
                                 ('expression-demo.js', 'AstraExpressionDemo', demo)]:
        (PREVIEW / name).write_text(
            '// Generated by expressions/build_preview_assets.py; edit the source JSON instead.\n'
            + f'globalThis.{variable} = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n',
            encoding='utf-8')
    if args.publish:
        destination = args.publish.resolve()
        destination.mkdir(parents=True, exist_ok=True)
        for name in RUNTIME_FILES:
            if destination != PREVIEW.resolve():
                shutil.copyfile(PREVIEW / name, destination / name)
        print(f'Published {len(RUNTIME_FILES)} preview assets to {destination}')
    else:
        print(f'Built offline resources in {PREVIEW}')


if __name__ == '__main__':
    main()
